name: Terraform VPC CIDR

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision VPC with CIDR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan -var="vpc_cidr=10.0.0.0/16"
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="vpc_cidr=10.0.0.0/16"
        working-directory: terraform/

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1

